import type { DependencyUpdate } from '../domain/dependencyUpdate.js';
import type { Llm } from '../providers/llm/llm.js';
import { isSecurityUpdate } from './classifier.js';

export interface ComposedPr {
  title: string;
  body: string;
  branch: string;
}

/** Branch name, e.g. `anneal/npm/axios-1.7.0`. */
export function branchName(update: DependencyUpdate): string {
  const pkg = update.package_name.replace(/[^a-zA-Z0-9._-]+/g, '-');
  return `anneal/${update.ecosystem}/${pkg}-${update.target_version}`;
}

/** PR title (F-017). security(deps) for CVE fixes, chore(deps) otherwise. */
export function prTitle(update: DependencyUpdate): string {
  const scope = isSecurityUpdate(update.cve) ? 'security' : 'chore';
  if (update.cve) {
    return `${scope}(deps): fix ${update.cve.id} in ${update.package_name}`;
  }
  return `${scope}(deps): update ${update.package_name} from ${update.current_version} to ${update.target_version}`;
}

/**
 * Compose the PR (F-017/F-018). Includes summary, reason, impact, changes, and an
 * Anneal evaluation footer with Confidence/Risk. Prose summary is LLM-enriched.
 */
export async function composePr(
  update: DependencyUpdate,
  changedFiles: string[],
  llm: Llm,
): Promise<ComposedPr> {
  const impact = update.impact;
  const llmSummary = await llm.generate({
    prompt: `[pr-body] Write a concise reviewer-facing summary for updating ${update.package_name} ` +
      `${update.current_version} -> ${update.target_version} (${update.update_type}).`,
    temperature: 0.3,
  });

  const reason = update.cve
    ? `Resolves ${update.cve.id} (${update.cve.severity}). ${update.cve.summary ?? ''}`.trim()
    : `Keeps ${update.package_name} current (${update.update_type} update).`;

  const body = [
    '## Summary',
    llmSummary && llmSummary !== 'OK' ? llmSummary : `Update ${update.package_name}.`,
    '',
    '## Reason',
    reason,
    '',
    '## Impact Analysis',
    impact
      ? `- Usage sites: ${impact.usageSites.length}\n` +
        `- Breaking change: ${impact.hasBreakingChange ? 'yes' : 'no'}\n` +
        `- Affected files:\n${impact.affectedFiles.map((f) => `  - ${f}`).join('\n') || '  - (none detected)'}`
      : '- (not analyzed)',
    '',
    '## Changes',
    changedFiles.map((f) => `- ${f}`).join('\n') || '- (none)',
    '',
    '## Test Result',
    update.ci
      ? `CI: ${update.ci.status}${update.ci.failureCategory ? ` (${update.ci.failureCategory})` : ''}`
      : 'CI: pending',
    '',
    '## Anneal Evaluation',
    `Confidence: ${impact ? impact.confidence.toFixed(2) : 'n/a'} / Risk: ${impact?.riskLevel ?? 'n/a'}`,
    '',
    '🔥 Auto-generated by Anneal',
  ].join('\n');

  return { title: prTitle(update), body, branch: branchName(update) };
}
