package usecase

import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/ZONO33LHD/anneal/domain/gateway"
	"github.com/ZONO33LHD/anneal/domain/model"
	"github.com/ZONO33LHD/anneal/domain/service"
)

// analyzeImpact は（scanner ポート経由で）使用箇所を特定し、リスクと
// 確信度（ドメインルール）を導出する。LLM は人間が読めるサマリーを付け足すだけ。
func (e *engine) analyzeImpact(ctx context.Context, rec model.DependencyUpdate) model.ImpactAnalysis {
	usage, err := e.scanner.UsageSites(rec.RepoPath, rec.PackageName)
	if err != nil {
		// 走査失敗を「利用箇所なし」と取り違えないよう警告する（部分結果で継続）。
		e.log.Warn(ctx, "source scan degraded", "package", rec.PackageName, "err", err)
	}
	breaking := rec.UpdateType == model.Major
	risk := service.DeriveRisk(rec.UpdateType, len(usage), breaking)
	confidence := service.DeriveConfidence(rec.UpdateType, len(usage))

	// 判断プロンプトは版で引く（T10）。採用/canary 版があればその版のテンプレートが、
	// 無ければ既定版 prompt_v1 が返る（PromptProvider が A1 フォールバックを担う）。
	prompt := fmt.Sprintf(
		e.prompts.For(rec.AgentVersion, gateway.PromptKeyImpact),
		rec.PackageName, rec.CurrentVersion, rec.TargetVersion, rec.UpdateType, len(usage), risk,
	)
	enriched, _ := e.llm.Generate(ctx, gateway.LLMRequest{Prompt: prompt, Temperature: 0.2})
	base := fmt.Sprintf("%s %s → %s (%s); %d usage site(s); risk %s.",
		rec.PackageName, rec.CurrentVersion, rec.TargetVersion, rec.UpdateType, len(usage), risk)
	summary := base
	if enriched != "" && enriched != "OK" {
		summary = base + " " + enriched
	}

	return model.ImpactAnalysis{
		UsageSites:        usage,
		HasBreakingChange: breaking,
		AffectedFiles:     usage,
		RiskLevel:         risk,
		Confidence:        confidence,
		Summary:           summary,
	}
}

// ciFailureSummary は CI 失敗の説明を LLM に依頼する（補足情報の付与のみ）。
func (e *engine) ciFailureSummary(ctx context.Context, logSummary string) string {
	out, _ := e.llm.Generate(ctx, gateway.LLMRequest{
		Prompt:      "[ci-summary] Summarize this CI failure and whether it is mechanically fixable:\n" + logSummary,
		Temperature: 0.2,
	})
	if out != "" && out != "OK" {
		return out
	}
	return logSummary
}

var branchUnsafe = regexp.MustCompile(`[^a-zA-Z0-9._-]+`)

// composePR は PR のタイトル・本文・ブランチを組み立てる。文章のサマリーは
// LLM で補強されるが、それ以外はすべて決定論的。
func (e *engine) composePR(ctx context.Context, rec model.DependencyUpdate, changed []string) (title, body, branch string) {
	pkg := branchUnsafe.ReplaceAllString(rec.PackageName, "-")
	branch = fmt.Sprintf("anneal/%s/%s-%s", rec.Ecosystem, pkg, rec.TargetVersion)

	title = fmt.Sprintf("chore(deps): update %s from %s to %s", rec.PackageName, rec.CurrentVersion, rec.TargetVersion)
	if rec.IsSecurityDriven() {
		title = fmt.Sprintf("security(deps): fix %s in %s", rec.CVE.ID, rec.PackageName)
	}

	llmSummary, _ := e.llm.Generate(ctx, gateway.LLMRequest{
		Prompt: fmt.Sprintf("[pr-body] Write a concise reviewer-facing summary for updating %s %s -> %s (%s).",
			rec.PackageName, rec.CurrentVersion, rec.TargetVersion, rec.UpdateType),
		Temperature: 0.3,
	})

	reason := fmt.Sprintf("Keeps %s current (%s update).", rec.PackageName, rec.UpdateType)
	if rec.CVE != nil {
		reason = strings.TrimSpace(fmt.Sprintf("Resolves %s (%s). %s", rec.CVE.ID, rec.CVE.Severity, rec.CVE.Summary))
	}

	var b strings.Builder
	b.WriteString("## Summary\n")
	if llmSummary != "" && llmSummary != "OK" {
		b.WriteString(llmSummary)
	} else {
		fmt.Fprintf(&b, "Update %s.", rec.PackageName)
	}
	b.WriteString("\n\n## Reason\n" + reason + "\n\n## Impact Analysis\n")
	if rec.Impact != nil {
		fmt.Fprintf(&b, "- Usage sites: %d\n- Breaking change: %s\n- Affected files:\n",
			len(rec.Impact.UsageSites), yesNo(rec.Impact.HasBreakingChange))
		if len(rec.Impact.AffectedFiles) == 0 {
			b.WriteString("  - (none detected)\n")
		}
		for _, f := range rec.Impact.AffectedFiles {
			fmt.Fprintf(&b, "  - %s\n", f)
		}
	} else {
		b.WriteString("- (not analyzed)\n")
	}
	b.WriteString("\n## Changes\n")
	if len(changed) == 0 {
		b.WriteString("- (none)\n")
	}
	for _, f := range changed {
		fmt.Fprintf(&b, "- %s\n", f)
	}
	conf, risk := "n/a", "n/a"
	if rec.Impact != nil {
		conf = fmt.Sprintf("%.2f", rec.Impact.Confidence)
		risk = string(rec.Impact.RiskLevel)
	}
	fmt.Fprintf(&b, "\n## Anneal Evaluation\nConfidence: %s / Risk: %s\n\n🔥 Auto-generated by Anneal", conf, risk)

	return title, b.String(), branch
}

func yesNo(b bool) string {
	if b {
		return "yes"
	}
	return "no"
}
